version: '3'

services:
  go:
    build: ./backend
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: mysql
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynet

volumes:
  mysql-data:

networks:
  mynet:
